[package]
name = "study_rust"
version = "0.1.0"
authors = ["yxwsbobo <yxwsbobo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand="0.6.5"